name: Deploy master branch

on:
    push:
        branches:
            - master

jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./sbx-manager-api
        strategy:
            matrix:
                node-version: [14.15.4]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: serverless deploy
              run: |
                  npm install -g serverless
                  npm ci
                  sls remove
              env:
                  # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
                  # or if using AWS credentials directly
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
